### ISSUE TITLE
Devoluciones

### ISSUE THREAD

**Issue by teran2410** [Echxvx2610/Biblioteca_Java#1]
Al tratar de devolver una revista la consola lanza un error, se necesita:

- Arreglar las devoluciones de revistas en el método devoluciones de la clase Biblioteca

**Comment by Echxvx2610** [comment]
![image](https://github.com/Echxvx2610/Biblioteca_Java/assets/99057175/2ddc2cbd-6dae-4d70-87b3-d96ef4be14ba)
talvez es por que en ningun momento dentro del metodo devoluciones() se instacia o hace referencia a la clase Revista

**Comment by teran2410** [comment]
Deja de andar de mamador y arregla el código

**Comment by Echxvx2610** [comment]
se actualizo logica de metodo, se cambio busqueda de libro o revista a documento, se creo un arraylist llamado Documento resultante de juntar el arraylist libros y revistas
